cmake_minimum_required(VERSION 3.02)

include(ExternalProject)

# LIEF as an External Project
# ===========================
set(LIEF_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/LIEF")
set(LIEF_INSTALL_DIR "${LIEF_PREFIX}")
set(LIEF_INCLUDE_DIRS "${LIEF_PREFIX}/include")

# LIEF static library
set(LIB_LIEF_STATIC
    "${LIEF_PREFIX}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}LIEF${CMAKE_STATIC_LIBRARY_SUFFIX}")

# URL of the LIEF repo (Can be your fork)
set(LIEF_GIT_URL "https://github.com/lief-project/LIEF.git")

# LIEF's version to be used (can be 'master')
set(LIEF_VERSION master)

# LIEF compilation 0.9.0
set(LIEF_CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DLIEF_TESTS=OFF
    -DLIEF_DOC=OFF
    -DLIEF_PYTHON_API=OFF
    -DLIEF_INSTALL_PYTHON=OFF
    -DLIEF_C_API=ON
    -DLIEF_EXAMPLES=OFF
    -DLIEF_COVERAGE=OFF
    -DLIEF_USE_CCACHE=ON
    -DLIEF_EXTRA_WARNINGS=OFF
    -DLIEF_LOGGING=OFF
    -DLIEF_ENABLE_JSON=OFF
    -DLIEF_DISABLE_FROZEN=OFF
    -DLIEF_ELF=ON
    -DLIEF_PE=OFF
    -DLIEF_MACHO=OFF
    -DLIEF_OAT=OFF
    -DLIEF_DEX=OFF
    -DLIEF_VDEX=OFF
    -DLIEF_ART=OFF
)

externalproject_add(LIEF
    PREFIX "${PACKER_LIEF_PREFIX}"
    GIT_REPOSITORY ${LIEF_GIT_URL}
    GIT_TAG ${LIEF_VERSION}
    INSTALL_DIR ${LIEF_INSTALL_DIR}
    CMAKE_ARGS ${LIEF_CMAKE_ARGS}
    BUILD_BYPRODUCTS ${LIEF_LIBRARIES}
    UPDATE_COMMAND ""
)
